stages:
    - run

run:
    image: ubuntu:18.04
    stage: run
    script:
        - bash ci.bash
    after_script:
        - bash <(curl -s https://codecov.io/bash) -t e087343b-5501-4bc0-aa2f-88e359393b99