stages:
    - test
    - final

test:
    script:
        - make
    when: always

final:
    script:
        - bash <(curl -s https://codecov.io/bash) -t <f4452f54-1eef-488a-9894-ce1dd4f6effa>
    when: always